### ISSUE TITLE
GenieException.toString() omits this.errorCode

### ISSUE THREAD

**Issue by skwslide** [Netflix/genie#161]
com.netflix.genie.common.exceptions.GenieException.toString() omits this.errorCode, sometimes leading to a value that includes only the class name, i.e. losing root cause information.

```
Caused by: com.netflix.genie.common.exceptions.GenieException:
    at com.netflix.genie.common.client.BaseGenieClient.executeRequest(BaseGenieClient.java:156)
    at com.netflix.genie.client.ExecutionServiceClient.getJob(ExecutionServiceClient.java:112)
    at com.netflix.genie.client.ExecutionServiceClient.waitForCompletion(ExecutionServiceClient.java:175)
    at com.netflix.ursula.merge.stats.MergeJob$GenieTask.waitForCompletion(MergeJob.java:200)
    ... 8 more
```

**Comment by skwslide** [comment]
Fixed by https://github.com/Netflix/genie/pull/170.
