### ISSUE TITLE
genie.jobs.cleanup.deleteArchiveFile = true causes error "Failed archiving directory for job"

### ISSUE THREAD

**Issue by jelez** [Netflix/genie#482]
Genie installed from jar: genie-app-3.0.1.jar

Starting genie as:
$ export JAVA_OPTS="-Djava.io.tmpdir=/opt/genie/tmp -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
$ exec java ${JAVA_OPTS} -jar /opt/genie/lib/genie-app-3.0.1.jar --spring.config.location=/opt/genie/config/

In /opt/genie/config/ I have application-dev.yml application-prod.yml application-s3.yml application.yml

Cluster YAML config looks like:

name: spark cluster
user: hadoop
version: 2.7.3
status: UP
tags:

type:yarn
ver:2.7.3
emr.cluster.release:emr-5.1.0
configs:
s3://mybucket/genie/clusters/j-XXXXXXXXXX/conf/hadoop/core-site.xml
s3://mybucket/genie/clusters/j-XXXXXXXXXX/conf/hadoop/mapred-site.xml
s3://mybucket/genie/clusters/j-XXXXXXXXXX/conf/hadoop/yarn-site.xml

I am getting the error below when I set deleteArchiveFile = true.
  jobs:
    cleanup:
      deleteArchiveFile: true
      deleteDependencies: true

2017-03-19 04:04:21.478 DEBUG 25360 --- [ taskExecutor-1] o.s.orm.jpa.JpaTransactionManager        : Participating in existing transaction
2017-03-19 04:04:21.483 DEBUG 25360 --- [ taskExecutor-1] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2017-03-19 04:04:21.483 DEBUG 25360 --- [ taskExecutor-1] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@61051db0]
2017-03-19 04:04:21.484 DEBUG 25360 --- [ taskExecutor-1] o.s.jdbc.datasource.DataSourceUtils      : Resetting read-only flag of JDBC Connection [ProxyConnection[PooledConnection[org.postgresql.jdbc.PgConnection@38d36c8d]]]
2017-03-19 04:04:21.484 DEBUG 25360 --- [ taskExecutor-1] o.s.orm.jpa.JpaTransactionManager        : Closing JPA EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@61051db0] after transaction
2017-03-19 04:04:21.484 DEBUG 25360 --- [ taskExecutor-1] o.s.orm.jpa.EntityManagerFactoryUtils    : Closing JPA EntityManager
2017-03-19 04:04:21.488 DEBUG 25360 --- [ taskExecutor-1] o.s.retry.support.RetryTemplate          : Checking for rethrow: count=5
2017-03-19 04:04:21.488 DEBUG 25360 --- [ taskExecutor-1] o.s.retry.support.RetryTemplate          : Retry failed last attempt: count=5
2017-03-19 04:04:21.488 ERROR 25360 --- [ taskExecutor-1] c.n.g.w.tasks.job.JobCompletionService   : Failed archiving directory for job: a8d32eda-0c58-11e7-94a9-0618a8b791c5

org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar!/:1.3]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166) ~[commons-exec-1.3.jar!/:1.3]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153) ~[commons-exec-1.3.jar!/:1.3]
        at com.netflix.genie.web.tasks.job.JobCompletionService.processJobDir(JobCompletionService.java:456) ~[genie-web-3.0.1.jar!/:3.0.1]
        at com.netflix.genie.web.tasks.job.JobCompletionService.lambda$handleJobCompletion$2(JobCompletionService.java:184) ~[genie-web-3.0.1.jar!/:3.0.1]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276) ~[spring-retry-1.1.3.RELEASE.jar!/:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157) ~[spring-retry-1.1.3.RELEASE.jar!/:na]
        at com.netflix.genie.web.tasks.job.JobCompletionService.handleJobCompletion(JobCompletionService.java:184) ~[genie-web-3.0.1.jar!/:3.0.1]
        at com.netflix.genie.web.tasks.job.JobCompletionHandler.handleJobCompletion(JobCompletionHandler.java:59) [genie-web-3.0.1.jar!/:3.0.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:223) [spring-context-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:144) [spring-context-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:106) [spring-context-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) [spring-context-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster$1.run(SimpleApplicationEventMulticaster.java:133) [spring-context-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by tgianos** [comment]
@jelez Thanks for the report.

Looks like it wasn't really enabling deleting the archive file rather it was a bug with creating the archive file itself when your system wasn't configured for sudo. We believed we've fixed it with #483 which is part of the 3.0.3 release I just cut. Could you retry with 3.0.3 instead of 3.0.1 and let us know if your issue is fixed?
