### ISSUE TITLE
Genie instance out of service due to database connection closed 

### ISSUE THREAD

**Issue by RajeshThallam** [Netflix/genie#666]
We use ELB to send tasks to a cluster of Genie nodes running on v3.0.8 with AWS Postgres RDS. Genie went out of service as the connections got closed. At the time of error, there were no issues with database and it was up and running.
Below is the stacktrace. Genie service was not recycled since 11/2/2017. Any clues to find the root cause? 

```
2017-12-19 03:19:54.069  INFO 15091 --- [nio-8080-exec-4] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2017-12-19 03:19:54.077  WARN 15091 --- [nio-8080-exec-4] o.s.jdbc.support.SQLErrorCodesFactory    : Error while extracting database product name - falling back to empty error codes

org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: This connection has been closed.
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:305) ~[spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:329) ~[spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.support.SQLErrorCodesFactory.getErrorCodes(SQLErrorCodesFactory.java:214) ~[spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:134) [spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:97) [spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:99) [spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:415) [spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:470) [spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:480) [spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.boot.actuate.health.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:110) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.boot.actuate.health.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:99) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:38) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.boot.actuate.endpoint.HealthEndpoint.invoke(HealthEndpoint.java:81) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.getHealth(HealthMvcEndpoint.java:162) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(HealthMvcEndpoint.java:136) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) [spring-webmvc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.37.jar!/:8.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:281) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115) [spring-boot-actuator-1.3.8.RELEASE.jar!/:1.3.8.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.37.jar!/:8.0.37]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:207) [spring-security-web-4.0.4.RELEASE.jar!/:4.0.4.RELEASE]

Caused by: org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:806) ~[postgresql-9.4.1211.jre7.jar!/:9.4.1211.jre7]
        at org.postgresql.jdbc.PgConnection.getMetaData(PgConnection.java:1271) ~[postgresql-9.4.1211.jre7.jar!/:9.4.1211.jre7]
        at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[tomcat-jdbc-8.0.37.jar!/:na]
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[tomcat-jdbc-8.0.37.jar!/:na]
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[tomcat-jdbc-8.0.37.jar!/:na]
        at com.sun.proxy.$Proxy89.getMetaData(Unknown Source) ~[na:na]
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:294) ~[spring-jdbc-4.2.8.RELEASE.jar!/:4.2.8.RELEASE]
        ... 85 common frames omitted
```

**Comment by mprimi** [comment]
Hello @RajeshThallam.
It is possible that connections get closed even if the database is reporting UP status. For example if the network between Genie servers and the database is down, but the network between the database and the health-check systems is up.

After throwing these exceptions, did Genie recover?
If it did, this would look like a network blip, you may ask AWS support for further details, it doesn't seem Genie-specific.
If it didn't recover, have you checked connectivity between Genie servers and the database? 
If connectivity is confirmed, can you try bringing up a new instance (this would tell us if the existing instances are in some sort of bad state where they can't reconnect).

The only scenario where we would want to treat this as a Genie issue is if:
 * Database connectivity is confirmed (i.e. opening a connection from Genie instance works)
 * Existing Genie instances don't manage to reconnect to the database

**Comment by RajeshThallam** [comment]
@mprimi, genie did not recover until we restarted the service. 
- Opening db connection from genie instance works
- Existing genie instances did not reconnect to the database. Error in the issue was the last message on genie log but the service was running. We stopped and restarted genie service on all the nodes for it to be back.

**Comment by tgianos** [comment]
@RajeshThallam Can you share your db connection pool settings?

Without seeing all details it looks like the app tried to grab/use a stale connection. I would suggest tweaking your connection pool settings to make sure old/stale connections are evicted and connections are tested before they're borrowed.

At Netflix in production we use the following settings:

```
spring:
  datasource:
    tomcat:
      min-idle: 5
      max-idle: 20
      max-active: 40
      validation-query: select 0;
      test-on-borrow: true
      test-on-connect: true
      test-on-return: true
      test-while-idle: true
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 10000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
```

Note: This is on Genie 3.2.x so you'd have to go back and make sure all these are accurate properties for the Spring version used with genie 3.0.x. Looks like 3.0.8 was on [Boot 1.3.8](https://docs.spring.io/spring-boot/docs/1.3.8.RELEASE/reference/htmlsingle/#common-application-properties)

**Comment by RajeshThallam** [comment]
Thanks @tgianos. We suspect the same - stale connections. Our db connection pool settings default to Spring version. Will tweak settings and check.

```
spring:
  datasource:
    password: 
    url: 
    username: genie
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
```

**Comment by RajeshThallam** [comment]
Stale db connections was the issue. Restarting genie services periodically (weekly/monthly) seems to fix the issue without changing default db connection settings.

**Comment by mprimi** [comment]
Happy that you resolved.
Restarting may mask the problem but I'd still recommend getting to the bottom of it and tweaking the database settings to solve it.
If for example your cluster grows or the load increases in the future, you'd end up cycling through more  connections than you do today, and this problem will come back to bite you again.
Just my 2 cents.
